### ISSUE TITLE
After all the invaders are gone an exception is thrown

### ISSUE THREAD

**Issue by ronbenyosef** [RDev16/Simple-Space-Invaders-Clone#2]
Add a win state after all the invaders have gone.

**Comment by devmaaj** [comment]
Greetings, 
I want to review the code and fix the issue, could I colaborate?

**Comment by devmaaj** [comment]
Following the game loop I see that ' tick  'method is called over and over in AlienManagement and uses the first position of aliens array to fill their controller and move on with loop, then I've added a 'if' validating the  aliens list size, now if the aliens list  is equals to 0 the end game state can be managed or winner message can be displayed.

**Comment by vmaffioli** [comment]
https://github.com/RDev16/Space-Invaders-Clone/pull/4

**Comment by vmaffioli** [comment]
https://github.com/RDev16/Space-Invaders-Clone/pull/4

**Comment by devmaaj** [comment]
Pull : https://github.com/RDev16/Space-Invaders-Clone/pull/4

**Comment by ronbenyosef** [comment]
> Greetings,
> I want to review the code and fix the issue, could I collaborate?

@vmaffioli Sure! I will test your commit (:

**Comment by ronbenyosef** [comment]
> Following the game loop I see that ' tick 'method is called over and over in AlienManagement and uses the first position of aliens array to fill their controller and move on with loop, then I've added a 'if' validating the aliens list size, now if the aliens list is equals to 0 the end game state can be managed or winner message can be displayed.

I've tested the code, I will merge it (: 
The issue will still be open because only the exception is handled, but there is no win state (:

**Comment by vmaffioli** [comment]
Ok, I will work in a new win state.

**Comment by devmaaj** [comment]
Please, could you assign this issue to me ?

**Comment by ronbenyosef** [comment]
> Please, could you assign this issue to me ?

Assigned

**Comment by vmaffioli** [comment]
Reading your edits I think the best is close  this issue because the  original exception was  resolved, please open a new issue to the new  task.

![image](https://user-images.githubusercontent.com/56659378/130002734-1c319517-d125-40fe-ad57-949039873041.png)

**Comment by devmaaj** [comment]
> I've tested the code, I will merge it (:
> The issue will still be open because only the exception is handled, but there is no win state (:

Please, close this issue and open a new one  to the task "add a winner state".
The original request was solved (AlienManager  exception handler)

![image](https://user-images.githubusercontent.com/56659378/130003034-122c7cee-8389-452a-8464-dfb06001c494.png)

thank you
