### ISSUE TITLE
Threre is no win state in the game, please add one

### ISSUE THREAD

**Issue by ronbenyosef** [RDev16/Simple-Space-Invaders-Clone#5]
Win state is the only thing missing to make this game an actual game. 

**The Problem:** After destroying all of the aliens nothing is happening, because there is no **win state**. Please add win state. 

**Guidelines:**

- You can add win state by going into the PlayState class and add the relevant conditions for winning. 
- For the UI, you can use the Button and Label classes for the winner UI. 
- Because of a poor design, the actions performed when pressing a button, have to be specified at the Button class inside the tick method.

@vmaffioli

**Comment by devmaaj** [comment]
Greetings, could you assign me? I want to colaborate 
thank you o/
